# Generated by Django 5.2.1 on 2025-07-02 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_cours", models.CharField(max_length=150)),
                ("code_cours", models.CharField(max_length=20)),
                ("credits", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Etudiant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_etudiant", models.CharField(max_length=150)),
                ("prenom_etudiant", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Programme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_programme", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Cheminement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "etudiant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="api.etudiant"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Prerequis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cours",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cours_principal",
                        to="api.cours",
                    ),
                ),
                (
                    "prerequis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cours_prerequis",
                        to="api.cours",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="etudiant",
            name="programme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.programme"
            ),
        ),
        migrations.AddField(
            model_name="cours",
            name="programme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.programme"
            ),
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_session", models.CharField(max_length=30)),
                ("total_credits", models.IntegerField()),
                (
                    "cheminement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.cheminement",
                    ),
                ),
                ("cours", models.ManyToManyField(blank=True, to="api.cours")),
            ],
        ),
    ]
