# Generated by Django 5.2.1 on 2025-07-03 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_coursparsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="numero_session",
            field=models.IntegerField(default=1),
        ),
    ]
