# Generated by Django 5.2.1 on 2025-07-03 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_session_numero_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="cours",
            name="est_optionnel",
            field=models.BooleanField(default=False),
        ),
    ]
