# Generated by Django 5.2.1 on 2025-07-04 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_cours_est_optionnel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="total_credits",
            field=models.IntegerField(default=0),
        ),
    ]
