# Generated by Django 5.2.1 on 2025-07-05 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_session_total_credits"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="session",
            name="cours",
        ),
    ]
