# Generated by Django 5.2.1 on 2025-07-05 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_remove_session_cours"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursparsession",
            name="cheminement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cours_sessions",
                to="api.cheminement",
            ),
        ),
    ]
