# Generated by Django 5.2.1 on 2025-07-08 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_coursparsession_cheminement"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="session",
            unique_together={("nom_session", "numero_session")},
        ),
        migrations.RemoveField(
            model_name="session",
            name="cheminement",
        ),
        migrations.RemoveField(
            model_name="session",
            name="total_credits",
        ),
    ]
