# Generated by Django 5.2.1 on 2025-07-08 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_session_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="session",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="session",
            name="cheminement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.cheminement",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="session",
            unique_together={("cheminement", "nom_session", "numero_session")},
        ),
    ]
