# Generated by Django 5.2.1 on 2025-07-09 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_session_unique_together_session_cheminement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursparsession",
            name="ignore",
            field=models.BooleanField(default=False),
        ),
    ]
