# Generated by Django 5.2.1 on 2025-07-09 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_coursparsession_ignore"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coursparsession",
            name="ignore",
        ),
        migrations.AlterUniqueTogether(
            name="session",
            unique_together={("nom_session", "numero_session")},
        ),
        migrations.RemoveField(
            model_name="session",
            name="cheminement",
        ),
    ]
