# Generated by Django 5.2.1 on 2025-08-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_remove_coursparsession_ignore_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursparsession",
            name="credits",
            field=models.IntegerField(default=0),
        ),
    ]
