# Generated by Django 5.2.1 on 2025-08-05 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_coursparsession_credits"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="coursparsession",
            unique_together={("cheminement", "cours")},
        ),
    ]
