# Generated by Django 5.2.1 on 2025-08-12 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_alter_coursparsession_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cours",
            options={"verbose_name": "Cours", "verbose_name_plural": "Cours"},
        ),
        migrations.AlterModelOptions(
            name="prerequis",
            options={"verbose_name": "Prérequis", "verbose_name_plural": "Prérequis"},
        ),
    ]
